### ISSUE TITLE
Area plots crashes webpage

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#204]
The newest rollout has caused problems with plotting area plots for the datasets that have not updated since the rollout of version [v2.3.0](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.0) 

It is not clear what the cause of this is but it looks like it's related to the npm update. this update did not go smoothly when rolling out the new code and the site was completely down for a while, giving only a blank page (not even an error). This was fixed by deleting the package-lock.json file addition to the npm-modules folder and letting both get rebuilt automatical. It seemed to work but now it can be seen that polts are not fully working and provide a blank page when accessed.

**Comment by htmlboss** [comment]
Kinda concerned about the npm issues...I'd need to see npm's logs to see exactly what happened. I'll attempt to re-do the npm stuff on Dory this week and see what happens. Anyways Chrome's debugger says it seems to be an issue with the timestamp component but I need to see this on my computer to get a usable stack trace instead of the optimized mess lol.

**Comment by htmlboss** [comment]
Yah so the issue is with Timepicker.jsx. Lemme see what I can find.

**Comment by Jeffreydaw** [comment]
resolved by rolling back to react 15 
see release [v2.3.1](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/tree/v2.3.1)
