### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by htmlboss** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#238]
[https://letsencrypt.org/getting-started/](https://letsencrypt.org/getting-started/)

[https://certbot.eff.org/lets-encrypt/ubuntutrusty-nginx](https://certbot.eff.org/lets-encrypt/ubuntutrusty-nginx)

**Comment by dwayne-hart** [comment]
Once I have a backup of the existing dory. I need to install a number of Python packages in order to install LetsEncrypt.

**Comment by dwayne-hart** [comment]
Unfortunately due to an issue with forward and reverse DNS lookup we are not able to use LetsEncrypt. 

I did configure a self signed certificate to allow people to use https for secure web traffic. The end user would receive a notification that the certificate should not be trusted due to it being self signed. 

The certificate will expire on Friday, February 12, 2021 at 1:50:02 PM Newfoundland Standard Time

![Screen Shot 2020-04-02 at 10 54 06 AM](https://user-images.githubusercontent.com/44408505/78254339-56699100-74d0-11ea-9269-0567da71193e.png)

**Comment by dwayne-hart** [comment]
I will now close this issue and create a new issue if we are able to resolve the DNS issue.
