### ISSUE TITLE
Unable to plot 3D variables with new Gulf dataset

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#254]
3D variables can't be plotted using the gulf dataset.

This includes transect plots

![image](https://user-images.githubusercontent.com/34169751/40625344-614e9424-628c-11e8-8d5a-c66fe798b59a.png)

**Comment by nsoontie** [comment]
Problem was with name of vertical dimension which was 'z' instead of 'deptht' or 'depth'. Gulf files now have 'depth' vertical dimension.  

PS @htmlboss  Should we include 'z' as possible vertical dimension?
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/a93d6c811b47d3869b7ce8846911621a785149a6/data/nemo.py#L17-L18

**Comment by nsoontie** [comment]
@NoahGallant-MUN Can we close this one?

**Comment by NoahGallant-MUN** [comment]
Yes, its been working since the change!
