### ISSUE TITLE
Layer UI - Data Overlapping Land when zoomed in

### ISSUE THREAD

**Issue by NoahGallant-MUN** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#531]
**Describe the bug**
At really high zoom levels the land is appearing underneath the data layer. In other words the data is no longer being masked

**To Reproduce**
Zoom in really far

**Expected behavior**
The data should follow the land, for example PEI should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/34169751/67910730-9d8ad900-fb62-11e9-8aba-1c7b3983267b.png)

**Comment by jamesprayner** [comment]
Data masking requires an entopo.nc file for that zoom level (resolution) to know what shape to mask for. We don't have these files for higher zoom levels. The white shapefile layer(s?) only display opaque tiles when the zoom level is high enough. They were designed to be drawn on top of the data layer so that masking wasn't required.

Hope this helps

**Comment by NoahGallant-MUN** [comment]
Thank you, I remember you letting me know before and I just have to implement it :)
