### ISSUE TITLE
Class 4 functionality - not displaying all global models in comparison

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#764]
Class 4 functionality not working properly. When selecting an observation profile the only comparison is with the GIOPS dataset. The option to compare with FOAM, HYCOM, etc. is not available. 
![image](https://user-images.githubusercontent.com/30048431/95110938-59f90180-0719-11eb-811d-b79b1c3f69dc.png)

http://navigator.oceansdata.ca/public/?query=%7B%22center%22%3A%5B%22-46.7041%22%2C%2245.6173%22%5D%2C%22class4%22%3A%5B%22class4_20200624_GIOPS_CONCEPTS_3.0_profile_273%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22modal%22%3A%22class4%22%2C%22names%22%3A%5B%224902455%20%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22climatology%22%3Afalse%2C%22dpi%22%3A144%2C%22error%22%3A%22none%22%2C%22forecast%22%3A%22best%22%2C%22models%22%3A%5B%5D%2C%22showmap%22%3Atrue%2C%22size%22%3A%2210x7%22%7D%2C%22time%22%3A%222233828800%22%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3A%22class4_20200624_GIOPS_CONCEPTS_3.0_profile%22%2C%22vectortype%22%3A%22class4%22%2C%22zoom%22%3A4%7D

**Additional context**

**Comment by douglatornell** [comment]
I think that PR #797 fixes this issue. See, for example:
http://navigator.oceansdata.ca:89/public/?query=%7B%22center%22%3A%5B%22-46.7041%22%2C%2245.6173%22%5D%2C%22class4%22%3A%5B%22class4_20190624_GIOPS_CONCEPTS_2.3_profile_652%22%5D%2C%22dataset%22%3A%22giops_day%22%2C%22depth%22%3A0%2C%22modal%22%3A%22class4%22%2C%22names%22%3A%5B%226902865%20%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22climatology%22%3Afalse%2C%22dpi%22%3A144%2C%22error%22%3A%22none%22%2C%22forecast%22%3A%22best%22%2C%22models%22%3A%5B%5D%2C%22showmap%22%3Afalse%2C%22size%22%3A%2210x7%22%7D%2C%22time%22%3A%222233828800%22%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3A%22class4_20190624_GIOPS_CONCEPTS_2.3_profile%22%2C%22vectortype%22%3A%22class4%22%2C%22zoom%22%3A4%7D

The query URL in the issue description no longer works because GIOPS 10-day forecast that includes 2020-06-24 is no longer available. Also 2020 class 4 datasets are not presently accessible as noted in issue #785.
