### ISSUE TITLE
Class 4s not available

### ISSUE THREAD

**Issue by Jeffreydaw** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#97]
The class 4s are not available on the production server but is available on the test server. 

This problem was noticed after a full system reboot last week (sept 13th). it is not clear if this was the cause the problem as the class 4s were not checked right before the reboot. 

This problem first appaired in v2.1.1 (but not right away we don't think )

**Comment by Jeffreydaw** [comment]
I spun up a version of the ocean navigation running in debug mode on my local computer and pointed the data source at the production server (dory).  I was able to view the class 4's without issue. but when I spun up a version, not in debug mode (12 threads) I was not able to view the class 4's.

**Comment by Jeffreydaw** [comment]
using the inspect elements option in crome I could see that the class 4 request times out after the time to first bit (TTFB) takes 1 minute.  But looking at the debug mode version (localhost:5000) the TTFB was 1.5 min before the content download took 1.6 ms and this worked. It seems that the debug mode is allowed to run for longer before a timeout error is registered.   


By putting the request 'localhost:5000/api/class4/' into the URL I was able to recive a list of the class 4's  
`{"name": "2017-09-10", "id": "class4_20170910_GIOPS_CONCEPTS_2.1_profile"}, {"name": "2017-09-09", "id": "class4_20170909_GIOPS_CONCEPTS_2.1_profile"}, {"name": "2017-09-08", "id": "class4_20170908_GIOPS_CONCEPTS_2.1_profile"}, {"name": "2017-09-07", "id": "class4_20170907_GIOPS_CONCEPTS_2.1_profile"}, {"name": "2017-09-06", "id": "class4_20170906_GIOPS_CONCEPTS_2.1_profile"}, {"name": "2017-09-05", "id": "class4_20170905_GIOPS_CONCEPTS_2.1_profile"},`
 but when useing the non debug verson 'localhost:5050/api/class4/' or the public one 'navigator.oceansdata.ca/api/class4/ ' I get a time out error

**Comment by Jeffreydaw** [comment]
I tested spinning up a mulity threaded version on my local computer. The config file was set for both the class 4 and the 'CLASS4_CATALOG_URL' and the 'CLASS4_URL' pointing at the test servre (Trinity) which is not having any class 4 problem. The result was interesting, at first it did not seem to work the class 4 was not available right away but the inspect elements network section indecated that the class4's took 1.5 min for the TTFB and then 0.77ms for the actually download. At this point the class 4s were availble to be selected. However  if I tried to view the class4's before the TTFB finished the class4's were not only not availabe but remained unavailabe even after the download had finished. though they were imeadaly available  after a refresh. (maybe a cache problem)

On a different note. The link below was generated form a local verson that was running with working class 4's (it was pointed at trinity) I then changed the URL so that it would load on Dory. The result was that the URL did load the windeowed view of the class4. But strangly when closing the windeow all the class 4 points for that day were on the map an could be selected. However the calendar dates still could not be selected.     
  [class 4](http://142.130.125.37/public/?query=%7B%22center%22%3A%5B%22-50.0000%22%2C%2253.0000%22%5D%2C%22zoom%22%3A4%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22time%22%3A568%2C%22variable%22%3A%22votemper%22%2C%22scale%22%3A%5B-5%2C30%5D%2C%22vectortype%22%3A%22class4%22%2C%22vectorid%22%3A%22class4_20170914_GIOPS_CONCEPTS_2.1_profile%22%2C%22subquery%22%3A%7B%22forecast%22%3A%22best%22%2C%22showmap%22%3Atrue%2C%22climatology%22%3Afalse%2C%22error%22%3A%22none%22%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A72%2C%22models%22%3A%5B%5D%2C%22forecast_name%22%3A%22Best%20Estimate%22%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22class4%22%2C%22names%22%3A%5B%224901747%22%5D%2C%22class4%22%3A%5B%22class4_20170914_GIOPS_CONCEPTS_2.1_profile%2F430%22%5D%7D)

**Comment by Jeffreydaw** [comment]
to see a list of the files accessed it create the calendar list put http://navigator.oceansdata/api/class4/ in the URL. 

Also Trinity has 2 fewer months worth of data that Dory

**Comment by Jeffreydaw** [comment]
Clide tested the 'crawl' that the python code that gets the class 4 files https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/a40cdd5acd8abe48401076db5f21aa54892192b9/oceannavigator/misc.py#L383
That is the function that gets called every time the web page loads (the function gets called when the [/api/class4](http://navigator.oceansdata/api/class4/) request is made)
the http://navigator.oceansdata.ca/thredds/catalog/class4/catalog.xml does not make the same call, it only makes one call to tomcat while the api call seems to make many.  This may be a result of crawl making a call for each file since it is using the list files in the xml file to make it's call(s). 

possible solutions :
* it is probably better to parse the existing XML file instead of making many calls
* have an array stored in a file on dory that will be pulled in when the web page loads instead of being generated and make the class 4 script update it if there are new files pulled down. 
* make a proper aggregate file using threads.

**Comment by clydeclements** [comment]
## Problem

From other observations, the issue with the Class 4 data appears to be a timeout of HTTP connections after 1 minute, which is happening before “processing” of the Class 4 data has finished.

To get a better idea of the current issue with the Class 4 data in Ocean Navigator, I took a closer look at one of the Python functions in the code, namely, the function `list_class4_files` in file `oceannavigator/misc.py`. That function is currently defined as:
```
  def list_class4_files():
      c = Crawl(app.config["CLASS4_CATALOG_URL"], select=[".*_GIOPS_.*.nc$"])

      result = []
      for dataset in c.datasets:
          value = dataset.name[:-3]
          date = datetime.datetime.strptime(value.split("_")[1], "%Y%m%d")
          result.append({
              'name': date.strftime("%Y-%m-%d"),
              'id': value
          })

      return result
```
I logged into the production server and started an interactive Python session as follows:
```
  export PATH=/opt/tools/anaconda/2/4.2.0/bin:$PATH
  ipython
```
First some initial setup (with prompts from `ipython` shown):
```
  In [1]: from thredds_crawler.crawl import Crawl

  In [2]: CLASS4_CATALOG_URL = "http://navigator.oceansdata.ca/thredds/catalog/class4/catalog.xml"
```
Testing the run-time of the `Crawl` function, I got:
```
  In [3]: %timeit -n 1 -r 1 c = Crawl(CLASS4_CATALOG_URL, select=[".*_GIOPS_.*.nc$"])
  1 loop, best of 1: 1min 5s per loop
```
The call to the function `Crawl` appears to be the culprit! It is taking longer than one minute to finish, resulting in the connection being closed before the list of dates can be generated to populate the calendar popup. A couple of points to note:

* The timeout is not happening in the above code; it is happening higher up in the chain (possibly with the uWSGI server component). Thus the above code is allowed to run to completion.

* Though only one timing result is shown above, in actuality I ran the test several times with all results exceeding one minute for completion.

## Solution

By default, the `Crawl` method is using 4 worker threads, but this can be increased. Some representative timing results are shown below:
```
  In [4]: %timeit -n 1 -r 1 c = Crawl(CLASS4_CATALOG_URL, select=[".*_GIOPS_.*.nc$"], workers=8)
  1 loop, best of 1: 47.3 s per loop

  In [5]: %timeit -n 1 -r 1 c = Crawl(CLASS4_CATALOG_URL, select=[".*_GIOPS_.*.nc$"], workers=16)
  1 loop, best of 1: 43.4 s per loop
```
Using 8 threads does drop the execution time below one minute; increasing to 16 threads decreases the time further, though not significantly. Bumping up the number of worker threads would likely get us out of the current problem, though not for long as the amount of Class 4 data is increasing daily. Thus this fix would only work for a short period before the crucial one minute limit would be hit again.

The generation of the list of Class 4 files is an expensive task, but it really only needs to be performed once per day since these files are only updated on a daily basis. The solution adopted here is to predetermine the list of Class 4 files in the daily cron job that pulls new data and store the list as a cache file. In the Ocean Navigator code, the `list_class4_files` then pulls in the list from that cache file. As a precaution against data corruption, the function acquires a read lock on the cache file before reading to ensure that the cron job is not simultaneously writing to the file.

See changes implemented in commits a39f5778785b2af4dad07ce41961e91d971b2a13 and 3fe912cb930b06119e758e63f58520680e187c9b.

**Comment by clydeclements** [comment]
## Problem

On October 11, 2017, it was noted that the Class 4 calendar pop-up in Ocean Navigator was only showing dates up to September 27, 2017. While Class 4 data lags behind by a few days (around 5 days?), it should not be behind by nearly two weeks!

## Fixes and Observations

I had a bug in the updated cron job that caused the rsync command to failed; specifically, I did not have the `PATH` variable set correctly. That's fixed now and I verified that the cron job is pulling down the latest data. As of today (October 12), that includes Class 4 data up to October 6.

But after the cron job updated the Class 4 files, it was observed that the Class 4 calendar pop-up in Ocean Navigator was still only showing data available for dates up to September 27. The reason for that was not immediately obvious to me. Some digging around revealed that this was due to caching by the web server Nginx. To elaborate, the URI request `/api/class4/` (which gives the list of Class 4 files) was not hitting the Python app at all because Nginx was returning its cached response for that request. One fix for that is to manually remove the file corresponding to Nginx's cached version of that request. The other fix is to simply wait because Nginx's cached version is set to expire 1 day from the time that it was created.

**Comment by Jeffreydaw** [comment]
this problem is now fixed. the dates seem to be going up without issue
